const pages = [
	{
		index: 0,
		title: 'Who goes there?',
		content: "[opening music]\n [wind]\n [clop clop clop]\n ARTHUR:  Whoa there!\n [clop clop clop]\n SOLDIER #1:  Halt! Who goes there?\n ARTHUR:  It is I, Arthur, son of Uther Pendragon, from the castle of Camelot. King of the Britons, defeater of the Saxons, Sovereign of all England!\n SOLDIER #1:  Pull the other one!\n ARTHUR:  I am, and this is my trusty servant Patsy. We have ridden the length and breadth of the land in search of knights who will join me in my court at Camelot. I must speak with your lord and master.\n SOLDIER #1:  What? Ridden on a horse?\n ARTHUR:  Yes!\n SOLDIER #1:  You're using coconuts!\n ARTHUR:  What?\n SOLDIER #1:  You've got two empty halves of coconut and you're bangin' 'em together.\n ARTHUR:  So? We have ridden since the snows of winter covered this land, through the kingdom of Mercia, through--\n SOLDIER #1:  Where'd you get the coconuts?\n ARTHUR:  We found them.\n SOLDIER #1:  Found them? In Mercia? The coconut's tropical!\n ARTHUR:  What do you mean?\n SOLDIER #1:  Well, this is a temperate zone."
	},
	{
		index: 1,
		title: '…Are you suggesting that coconuts migrate?',
		content: "ARTHUR:  The swallow may fly south with the sun or the house martin or the plover may seek warmer climes in winter, yet these are not strangers to our land?\n SOLDIER #1:  Are you suggesting coconuts migrate? Not at all. They could be carried.\n SOLDIER #1:  What? A swallow carrying a coconut?\n ARTHUR:  It could grip it by the husk\n SOLDIER #1:  It's not a question of where he grips it! It's a simple question of weight ratios! A five ounce bird could not	carry a one pound coconut.\n ARTHUR:  Well, it doesn't matter. Will you go and tell your master that Arthur from the Court of Camelot is here?\n SOLDIER #1:  Listen. In order to maintain air-speed	velocity, a swallow needs to beat its wings forty-three times every	second, right?\n ARTHUR:  Please!\n SOLDIER #1:  Am I right?\n ARTHUR:  I'm not interested!\n SOLDIER #2:  It could be carried by an African swallow!\n SOLDIER #1:  Oh, yeah, an African swallow maybe, but not a European swallow. Thats my point.\n SOLDIER #2:  Oh, yeah, I agree with that.\n ARTHUR:  Will you ask your master if he wants to join my	court at Camelot?!\n SOLDIER #1:  But then of course, uh, African swallows are	non-migratory.\n SOLDIER #2:  Oh, yeah.\n SOLDIER #1:  So, they couldn't bring a coconut back	anyway.\n [clop clop clop]\n SOLDIER #2:  Wait a minute! Supposing two swallows carried it together?\n SOLDIER #1:  No, they'd have to have it on a line.\n SOLDIER #2:  Well, simple! They'd just use a strand ofcreeper!\n SOLDIER #1:  What, held under the dorsal guiding feathers?\n SOLDIER #2:  Well, why not?"
	},
	{
		index: 2,
		title: 'Bring out your dead!',
		content: "[thud]\n [clang]\n CART MASTER:  Bring out your dead!\n [clang]\n Bring out your dead!\n [clang]\n Bring out your dead!\n [clang]\n Bring out your dead!\n [clang]\n Bring out your dead!\n [cough cough...]\n [clang]\n [...cough cough]\n Bring out your dead!\n [clang]\n Bring out your dead!\n [clang]\n Bring out your dead! Nine pence.\n [clang]\n Bring out your dead!\n [clang]\n Bring out your dead!\n [clang]  Bring out...\n [rewr!]  ...your dead!\n [rewr!]\n [clang]\n Bring out\n your dead!\n CUSTOMER:  Here's one.\n CART MASTER:  Nine pence.\n DEAD PERSON:  I'm not dead!"
	},
	{
		index: 3,
		title: 'I\'m not dead yet!',
		content: "CART MASTER:  What?\n CUSTOMER:  Nothing. Heres your nine pence.\n DEAD PERSON:  I'm not dead!\n CART MASTER:  'Ere. He says he's not dead!\n CUSTOMER:  Yes, he is.\n DEAD PERSON:  I'm not!\n CART MASTER:  He isn't?\n CUSTOMER:  Well, he will be soon. Hes very ill.\n DEAD PERSON:  I'm getting better!\n CUSTOMER:  No, you're not. Youll be stone dead in a moment.\n CART MASTER:  Oh, I can't take him like that. Its against regulations.\n DEAD PERSON:  I don't want to go on the cart!\n CUSTOMER:  Oh, don't be such a baby.\n CART MASTER:  I can't take him.\n DEAD PERSON:  I feel fine!\n CUSTOMER:  Well, do us a favor.\n CART MASTER:  I can't.\n CUSTOMER:  Well, can you hang around a couple of minutes? He won't be long.\n CART MASTER:  No, I've got to go to the Robinsons. Theyve lost nine today.\n CUSTOMER:  Well, when's your next round?\n CART MASTER:  Thursday.\n DEAD PERSON:  I think I'll go for a walk.\n CUSTOMER:  You're not fooling anyone, you know. Look. Isnt\n there something you can do?\n DEAD PERSON:   [singing]  I feel happy. I feel happy.\n [whop]\n CUSTOMER:  Ah, thanks very much.\n CART MASTER:  Not at all. See you on Thursday.\n CUSTOMER:  Right. All right."
	},
	{
		index: 4,
		title: 'I\'m thirty-seven!',
		content: "[thud]\n [King Arthur music]\n [thud thud thud]\n [King Arthur music stops]\n ARTHUR:  Old woman!\n DENNIS:  Man!\n ARTHUR:  Man. Sorry. What knight lives in that castle over there?\n DENNIS:  I'm thirty-seven.\n ARTHUR:  I-- what?\n DENNIS:  I'm thirty-seven. Im not old.\n ARTHUR:  Well, I can't just call you 'Man'.\n DENNIS:  Well, you could say 'Dennis'.\n ARTHUR:  Well, I didn't know you were called 'Dennis'.\n DENNIS:  Well, you didn't bother to find out, did you?\n ARTHUR:  I did say 'sorry' about the 'old woman', but from the behind you looked--\n DENNIS:  What I object to is that you automatically treat me like an inferior!\n ARTHUR:  Well, I am King!\n DENNIS:  Oh, King, eh, very nice. And how d'you get that, eh? By exploiting the workers! By anging on to outdated imperialist dogma which perpetuates the economic and social differences in our society. If there's ever going to be any progress with the--\n WOMAN:  Dennis, there's some lovely filth\n down here. Oh! How d'you do?\n ARTHUR:  How do you do, good lady? I am Arthur, King of the Britons. Whos castle is that?\n WOMAN:  King of the who?"
	},
	{
		index: 5,
		title: 'The who?',
		content:"ARTHUR:  The Britons.\n WOMAN:  Who are the Britons?\n ARTHUR:  Well, we all are. We are all Britons, and I am your king.\n WOMAN:  I didn't know we had a king. I thought we were an autonomous collective.\n DENNIS:  You're fooling yourself. Were living in a dictatorship: a self-perpetuating autocracy in which the working classes--\n WOMAN:  Oh, there you go bringing class into it again.\n DENNIS:  That's what it's all about. If only people would hear of--\n ARTHUR:  Please! Please,\n good people. I am in haste. Who lives in that castle?\n WOMAN:  No one lives there.\n ARTHUR:  Then who is your lord?\n WOMAN:  We don't have a lord.\n ARTHUR:  What?\n DENNIS:  I told you. Were an anarcho-syndicalist commune. We take it in turns to act as a sort of executive officer for the week,...\n ARTHUR:  Yes.\n DENNIS:  ...but all the decisions of that officer have to be ratified at a special bi-weekly meeting...\n ARTHUR:  Yes, I see.\n DENNIS:  ...by a simple majority in\n the case of purely internal affairs,...\n ARTHUR:  Be quiet!\n DENNIS:  ...but by a two-thirds majority in the case of more major--\n ARTHUR:  Be quiet! I order you to be quiet!\n WOMAN:  Order, eh? Who does he think he is? Heh.\n ARTHUR:  I am your king!\n WOMAN:  Well, I didn't vote for you.\n ARTHUR:  You don't vote for kings.\n WOMAN:  Well, how did you become King, then?"
	},
	{
		index: 6,
		title: 'The French...',
		content: "[King Arthur music]\n [clop clop clop]\n ARTHUR:  Halt!\n [horn]\n Hallo!\n [pause]\n Hallo!\n FRENCH GUARD:  Allo! Who is eet?\n ARTHUR:  It is King Arthur, and these are my Knights of the Round Table. Whose castle is this?\n FRENCH GUARD:  This is the castle of my master, Guy de Loimbard.\n ARTHUR:  Go and tell your master that we have been charged by God with a sacred quest. If he will give us food and shelter for the night, he can join us in our quest for the Holy Grail.\n FRENCH GUARD:  Well, I'll ask him, but I don't think he'll be very keen. Uh, he's already got one, you see.\n ARTHUR:  What?\n GALAHAD:  He says they've already got one!\n ARTHUR:  Are you sure he's got one?\n FRENCH GUARD:  Oh, yes. Its very nice-a. (I told him we already got one.)\n FRENCH GUARDS:   [chuckling]\n ARTHUR:  Well, u-- um, can we come up and have a look?\n FRENCH GUARD:  Of course not! You are English types-a!\n ARTHUR:  Well, what are you, then?\n FRENCH GUARD:  I'm French!\n Why do think I have this outrageous accent, you silly king-a?!\n GALAHAD:  What are you doing in England?\n FRENCH GUARD:  Mind your own business!"
	},
	{
		index: 7,
		title: 'The grail!',
		content: "ARTHUR:  If you will not show us the Grail, we shall take your castle by force!\n FRENCH GUARD:  You don't frighten us, English pig-dogs! Go and boil your bottom, sons of a silly person. I blow my nose at you, so-called Arthur King, you and all your silly English k-nnnnniggets. Thpppppt! Thppt! Thppt!\n GALAHAD:  What a strange person.\n ARTHUR:  Now look here, my good man--\n FRENCH GUARD:  I don't wanna talk to you no more, you empty headed animal food trough wiper! I fart in\n your general direction! Your mother was a hamster and your father smelt of elderberries!\n GALAHAD:  Is there someone else up there we could talk to?\n FRENCH GUARD:  No. Now, go away, or I shall taunt you a second time-a!\n [sniff]\n ARTHUR:  Now, this is your last chance. Ive been more than reasonable.\n FRENCH GUARD:  (Fetchez la vache.)\n OTHER FRENCH GUARD:  Quoi?\n FRENCH GUARD:  (Fetchez la vache!)\n [mooo]\n ARTHUR:  If you do not agree to my commands, then I shall--\n [twong]\n [mooooooo]\n Jesus Christ!\n KNIGHTS:  Christ!\n [thud]\n Ah! Ohh!...\n ARTHUR:  Right! Charge!\n KNIGHTS:  Charge!\n [mayhem]\n FRENCH GUARD:  Hey, this one is for your mother! There you go.\n \n [mayhem]\n FRENCH GUARD:  And this one's for your dad!\n ARTHUR:  Run away!\n KNIGHTS:  Run away!"
	},
	{
		index: 8,
		title: 'I\'ll tear them apart!',
		content: "FRENCH GUARD:  Thppppt!\n FRENCH GUARDS:   [taunting]\n LANCELOT:  Fiends! I'll tear them apart!\n ARTHUR:  No, no. No, no.\n BEDEVERE:  Sir! I have a plan, sir.\n Later...\n [wind]\n [saw saw saw saw saw saw saw saw saw saw saw saw saw saw saw saw]\n \n [clunk]\n [bang]\n [rewr!]\n [squeak squeak squeak squeak squeak squeak squeak squeak squeak squeak]\n [rrrr rrrr rrrr]\n [drilllll]\n [sawwwww]\n [clunk]\n [crash]\n [clang]\n [squeak squeak squeak squeak squeak...]\n [creak]\n FRENCH GUARDS:   [whispering]\n C'est un lapin, lapin de bois. Quoi? Un cadeau. What? A present. Oh, un cadeau. Oui, oui. Allons-y. What? Let's go. Oh. On y va. Bon magne. Over here...\n [squeak squeak squeak squeak squeak...]\n [clllank]\n ARTHUR:  What happens now?"
	},
	{
		index: 9,
		title: 'A large, wooden badger',
		content: "BEDEVERE:  Well, now, uh, Lancelot, Galahad, and I, uh, wait until nightfall, and then leap out of the rabbit, taking the French, uh, by surprise. Not only by surprise, but totally unarmed!\n ARTHUR:  Who leaps out?\n BEDEVERE:  U-- u-- uh, Lancelot, Galahad, and I, uh, leap out of the rabbit, uh, and uh...\n ARTHUR:  Ohh.\n BEDEVERE:  Oh. Um, l-- look, i-- i-- if we built this large wooden badger--\n [clank]\n [twong]\n ARTHUR:  Run away!\n KNIGHTS:  Run away! Run away! Run away!\n Run away! Run away! Run away! Run away!\n [CRASH]\n FRENCH GUARDS:  Oh, haw haw haw haw! Haw! Haw haw heh..."
	}
]

export default pages
